### ISSUE TITLE
Setting Up DELTA : cd vagrant/

### ISSUE THREAD

**Issue by Cyb3rSn0rlax** [OpenNetworkingFoundation/DELTA#29]
![image](https://user-images.githubusercontent.com/18106793/34626707-c705221c-f255-11e7-9048-d8c741b5e344.png)
I think, if I am right about the vagrant directory, that the command 
cd vagrant/
should be changed to cd ../vagrant/
Then 
vangrant up
Correct me if I am wrong and explain please !

**Comment by toghrulrr** [comment]
Yes, you are right.
