### ISSUE TITLE
Host agent can't connect to Agent manager

### ISSUE THREAD

**Issue by ZhiYiFang** [OpenNetworkingFoundation/DELTA#40]
Hi,
I am very interested with this project and I am trying to use this tool in my own machine. My testing environment is all-in-one. But when I try to run test-advanced-topo.py. I find that the virtual host in topology created by mininet can't connect with my real machine. I tried to modify the code of test-advanced-topo.py but failed.

**Comment by SeungwonWoo** [comment]
Hello,
I think that is a routing problem.
Can you check the routing table in your AgentManager?
It must have a following routing rule: 
"sudo route add -net 10.0.1.0/24 gw 10.0.3.13 dev lxcbr0"

**Comment by ZhiYiFang** [comment]
Yeah, I have already add this rule to my AgentManager. What is strange is that my AgentManager can communicate with the root node defined in test-advanced-topo.py, but h1 cant't communicate with the root node. Oh, by the way, I use virtualbox to establish my experiment environment and I also use ssh just like the guide in the first page. Should I change to lxc?

**Comment by SeungwonWoo** [comment]
Now, we don't support the virtualbox-based environment.
So, you have to change your environment from virtualbox to lxc.
I'm sorry about that.
Thank you.

**Comment by ZhiYiFang** [comment]
Got it. Thank you!
